# Generated by Django 5.2 on 2025-04-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veterinary_billing.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veterinary_billing.mascota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=(0, 0), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_Cliente',
            field=models.CharField(default='Nombre Genérico', max_length=150),
            preserve_default=False,
        ),
    ]
