# Generated by Django 3.1.12 on 2025-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exported',
            field=models.BooleanField(default=False, verbose_name='Exportado a Excel/PDF'),
        ),
    ]
