# Generated by Django 3.1.12 on 2025-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Nombre del Dueño')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Teléfono del Dueño')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Email del Dueño')),
                ('appointment_type', models.CharField(choices=[('GENERAL', 'Consulta General'), ('EMERGENCY', 'Emergencia'), ('VACCINATION', 'Vacunación'), ('GROOMING', 'Peluquería'), ('SURGERY', 'Cirugía'), ('CHECKUP', 'Control')], default='GENERAL', max_length=20, verbose_name='Tipo de Cita')),
                ('appointment_date', models.DateField(verbose_name='Fecha de la Cita')),
                ('appointment_time', models.TimeField(verbose_name='Hora de la Cita')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Síntomas')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
