# Generated by Django 5.1.6 on 2025-05-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
