# Generated by Django 3.1.12 on 2025-05-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0002_alter_pet_id'),
        ('veterinary_pets', '0002_auto_20250408_2027'),
    ]

    operations = [
    ]
