# Generated by Django 5.2 on 2025-04-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0002_alter_pet_id'),
        ('veterinary_pets', '0002_auto_20250408_2027'),
    ]

    operations = [
    ]
