# Generated by Django 5.1.6 on 2025-05-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0004_alter_appointment_id_alter_medicalrecord_id_and_more'),
        ('veterinary_pets', '0004_auto_20250511_1728'),
    ]

    operations = [
    ]
