# Generated by Django 5.1.7 on 2025-05-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0003_merge_20250523_1018'),
        ('veterinary_pets', '0004_auto_20250511_1728'),
    ]

    operations = [
    ]
